### ISSUE TITLE
Promo Materials Checklist

### ISSUE THREAD

**Issue by wjamanda** [W4S-2021/workathon-handbook#7]
- [x] The Workathon Explained (stuff on readme)
- [x] email for volunteer recruiting 
  - [x] qualtrics survey
- [x] email for potential donors
- [x] video clips 
  - [x] raw footage
  - [x] edited version
- [x]  NDA from EJM
